### PR TITLE
add jieba tokenizer for Chinese

### PR DESCRIPTION
**Pull request by vincascm**
add jieba tokenizer for Chinese

### CODE REVIEW

**Comment by valeriansaliou** [comment]
Hello there! Your code is being Chinese-specific, which is not fine by me in terms of code hygiene. Can you also explain the purpose of this PR? Not familiar with the Jieba tokenizer.

**Comment by vincascm** [comment]
@valeriansaliou  
1. Chinese do not have a trivial word segmentation process . <https://en.wikipedia.org/wiki/Text_segmentation> 

2. jieba is a widely used Chinese tokenizer. <https://github.com/fxsjy/jieba#jieba-1>
3. may add special feature for Chinese.

**Comment by sftblw** [comment]
It is common to use tokenizer in CJK, even in elasticsearch [(google search of es + mecab tokenizer)](https://www.google.com/search?q=elasticsearch+mecab). As an example, NLP library spaCy requires external tokenizer installed in system for...

chinese | japanese | korean
-|-|-
[jieba](https://github.com/explosion/spaCy/blob/master/spacy/lang/zh/__init__.py) | mecab via fugashi | mecab-ko via natto-py

**Comment by dzcpy** [comment]
Have you guys found a solution for Chinese tokenizing?

**Comment by hajiuxbz** [comment]
Hope to merge

**Comment by rcy17** [comment]
One and a half years later...... Sincerely hope to merge.

**Comment by valeriansaliou** [comment]
Thanks for the PR, sorry it took so much time. Currently updating the jieba library to latest and refactoring code to make it an optional feature, as not all Sonic users need Chinese tokenization support (the library adds some size overhead).

**Pull request merged**
