### PR TITLE
List all words from the bucket control operator

### PR DESCRIPTION
**Pull request by trkohler**
resolve https://github.com/valeriansaliou/sonic/issues/177

### CODE REVIEW

**Comment by trkohler** [comment]
if possible, could you please [add hacktoberfest label to the PR](https://hacktoberfest.com/participation/#pr-mr-details)?
because otherwise it won't be count for me.

**Comment by valeriansaliou** [comment]
Thank you for the PR. The label has been added. I'm currently in holidays / so AFK, I'll review and merge this when I am back.

**Comment by trkohler** [comment]
thanks, sure. no hurry!

just FYI, that's from the hacktober site:
> MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR BE LABELED “HACKTOBERFEST-ACCEPTED.”

probably label needs to be changed to `hacktoberfest-accepted` to be counted because I guess there is some robot watching those and currently this PR is not counted in the dashboard.

**Comment by valeriansaliou** [comment]
Label updated, is it okay now?

**Comment by trkohler** [comment]
yes! it's accepted by hacktoberfest, now I would patiently wait for you to be back and review.

**Comment by trkohler** [comment]
@valeriansaliou gentle ping on my PR in case you forgot about it 👀

**Comment by valeriansaliou** [comment]
Still in holidays, it’s on my todo to review no worries ;)

**Comment by valeriansaliou** [comment]
Will merge now, some refactors are on the way, eg. moving the LIST command from the Control channel to the Search channel.

**Comment by valeriansaliou** [comment]
Released Sonic `v1.4.0` w/ the `LIST` command available in `search` mode. Also added support for `.list()` in `node-sonic-channel`.

**Pull request merged**
