### PR TITLE
Adding docker image for ARM

### PR DESCRIPTION
**Pull request by PovilasID**
Hey,

I would love to run this on ARM without having to build the container locally.
I added a tag that will build docker image for ARM based systems in parallel to x86.

### CODE REVIEW

**Comment by ryanccn** [comment]
You forgot to install QEMU and Buildx :p

**Comment by pandaninjas** [comment]
https://github.com/PovilasID/sonic/pull/1 proposed solution

**Comment by PovilasID** [comment]
@ryanccn you are right ops...
@pandaninjas I have not tested it... and would have relied on github actions like so:
```
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
```
but I am curious if this works so I approved the merge :)

**Comment by ryanccn** [comment]
@PovilasID Yeah I think you are usually supposed to be using the actions

**Comment by bendangelo** [comment]
Can this be merged in?

**Comment by valeriansaliou** [comment]
So, I've merged this and the build seems to be working fine so far, but it's been 30min it's running, which is not acceptable. I'll finish a build and release of a Sonic Docker ARM64 image as of `v1.4.7` and then pull out the ARM64 builder for future versions, until GitHub Actions provides native ARM64 runners. Won't be using QEMU for builds unfortunately as Sonic is just too large of a project to compile over an emulator.

**Comment by PovilasID** [comment]
Why does it matter how long does it build? Does it time out? 
The point of this adding arm support was so we get updates easily. We can build from arm source it is just a waste of time every time if there is an update.
Also I fairly certain that with build cashing, which seams to be enabled on this project, this would be a problem only on the first container build.

**Pull request merged**
