### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by pleshevskiy**
Added built-in attribute that deny some rust lints and all clippy rules (with some exceptions) and fixed all moments in the code.

These changes should reduce a bit memory allocation

### CODE REVIEW

**Comment by valeriansaliou** [comment]
Thank you for that. I've not forgotten about this, and will take care of reviewing it and merging it whenever I have a slot of time :) Been quite busy lately on other priorities, this is still stacked in my email inbox so I will not forget about that!

**Comment by pleshevskiy** [comment]
I see that you are actively working with "Makers For Life" project. Feel free to contact me if I can help something.

**Comment by pleshevskiy** [comment]
just resolved conflicts :)

**Comment by pleshevskiy** [comment]
@valeriansaliou I've rebased and pushed new changes. Could you take the time to look at this PR? I think the clippy tool is very important because it gives us very useful clues that you don't always think of the first time.

**Review by valeriansaliou — APPROVED** [review]
LGTM

**Pull request merged**
